test("Test error", () => {
  throw new Error("Test error");
});
